name: caver-js rc workflow
on:
  push:
    tags:
      - v*.*.*-*

jobs:
  workflow_publish:
    name: workflow_publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get git tag version
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Verify version between tag and file
        run: |
          TAG_VERSION = ${{ steps.vars.outputs.tag }}
          echo "tag version is " $TAG_VERSION

          file_version=v$(${GITHUB_WORKSPACE}/.github/script.sh)
          echo "file version is " $file_version

          if [ $file_version == ${TAG_VERSION%-*} ]; then
            echo "verification pass"
          else
            echo "It's not same version."
            exit 1
          fi
