name: caver-js test workflow
on:
  pull_request:
    branches-ignore:
      - /release\/.*/
      - master
    types: [opened, synchronize]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12.21.0

      - name: Cache node modules
        uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: npm-packages-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install

      - name: Run Lint
        run: npm run lint
        if: ${{ always() }}

      - name: Run test code
        run: npm test
        if: ${{ always() }}

      - name: Run test on Web env
        run: |
          sudo apt update
          sudo apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
          cd ./test/test-web
          ./prepareWebTest.sh
          npm run cypress:run
          ./terminateTest.sh
        if: ${{ always() }}
